### ISSUE TITLE
On hover increase size/scale of one Path

### ISSUE THREAD

**Issue by ListeH** [South-Paw/react-vector-maps#23]
Hi man,
great library, but I have one question. How I achieve to increase scale / size of one path (region in my map) on hover and not to be hided by another path which are higher?. I need this behaviour, but unfortunately I did not achieve it :(
Thanks

**Comment by South-Paw** [comment]
Hi,

I had a little play around with some of the examples on the docs site but I wasn't able to come up with much useful.

using `transform: scale(1.5)` on a layers hover CSS does work, but the origin it scales from is the top-left of the svg - I believe there may be a way to change the transform origin in CSS but I don't know it off the top of my head sorry.

**Comment by ListeH** [comment]
When you set to path ` transition: all 1s; transform-origin: 50% 50%;` and on hover ` transform: scale(1.1);` it looks good. But in component I have to change sort of regions every time I hover one of region, because last regions have always higher z-index

**Comment by ListeH** [comment]
Btw. is there any possibilities, how can I achieve that my canvas will be bigger? Now is canvas really close to my paths, and there is no padding in that svg, so when I increase one region, he is out of canvas and is cropped

**Comment by South-Paw** [comment]
you could try set the css z-index of every path and then increase the z-index of the one you're hovering so its on top.

as for it being cropped you could trying fiddling with overflow on the svg element or it's parent and see what happens

**Comment by ListeH** [comment]
Man that overflow is good point, nice! But for z-index I doubt that z index is working on path, but thanks

**Comment by South-Paw** [comment]
you may need to position relative the parent svg element when z-indexing the child paths

glad to hear you've mostly got it working though!
