### ISSUE TITLE
Facing issue with onMouseOut event. Its not firing when the mouse is out of the map

### ISSUE THREAD

**Issue by msraviteja123** [South-Paw/react-vector-maps#30]
I was facing issue while showing tooltip over the country. Tooltip is not hiding when the mouse is out of the map

```
const layerProps = {
    onMouseOver: countryHover,
    onMouseMove: MouseMove,
    onMouseOut: hideDetails,
  };
  const hideDetails = (e) => {
    console.log('mouse out');
    setDisplay({
      display: false,
      tooltipY: 0,
      tooltipX: 0,
    });
  };
  
  <Map>
          <VectorMap
            {...svgmap}
            currentLayers={['in', 'us']}
            layerProps={layerProps}
          />
        </Map>
```

**Comment by South-Paw** [comment]
The layer props are spread directly on to the child path elements (ie; the component doesn't use/adjust/play with them at all) so any issues you're facing with events is something to do with your implementation of them.

#21 has some pseudo code that may help you with implementing tooltips
#19 links to an older example with tooltips that worked at the time

Feel free to reply here and I can try help a little, but I'm closing the issue as it's not a problem with the component
