### ISSUE TITLE
Safari Vector Maps

### ISSUE THREAD

**Issue by D1noDen** [South-Paw/react-vector-maps#31]
how to display a Vector Map in the Safari browser?

**Comment by South-Paw** [comment]
This is a [React](https://react.dev/) package, so it's imported when you are using React to build you app/site.

The README explains how to install and set up the package - however I cannot provide any support if you don't already have a understanding of npm/yarn and React. This is just prerequisite knowledge before using any React package.

If you want to learn about SVGs, they work in pretty much any vendor's browser - here's the [MDN guide to SVGs](https://developer.mozilla.org/en-US/docs/Web/SVG) to get you started.
