### ISSUE TITLE
Converter issue

### ISSUE THREAD

**Issue by SSnoopy22** [South-Paw/react-vector-maps#32]
Hi, I have been trying to convert an svg file I created via draw.io to a vector file, but whenever I put it in the converter I get back a blank image. The only point in which I get back an image is if my image is only made up of dotted lines. Can you please explain how the converter works?

**Comment by South-Paw** [comment]
Sounds like your [your SVG does not meet all the requirements](https://react-vector-maps.netlify.app/converter) mentioned at the top of the converter page

> - `width` and `height` are required attributes on the <svg /> element.
> - The SVG is assumed to have a viewBox origin of `0 0` and uses the given `width` and `height` as the viewBox maximum values.
> - Only `<path />` elements will be converted to JSON.
> - `id` and `d` attributes are required on all path elements and the id must be unique for each path.
> - A `title` attribute on a path element will be used as the layers `name` field. If no title is present, the `id` will be capitalized and used.
> If your file doesn't meet these requirements then the output may be unexpected or incorrect 😉

Without a copy of the SVG file in question though, I couldn't tell you what the exact problem is
