### ISSUE TITLE
Docs website is down.

### ISSUE THREAD

**Issue by pka420** [South-Paw/react-vector-maps#34]

**Comment by South-Paw** [comment]
Could you provide some more detail please?

https://react-vector-maps.netlify.app appears to be working fine

Will reopen if there is a problem

**Comment by pka420** [comment]
Oh man, 

I tried the documentation link in README that points to `https://react-vector-maps.netlify.com/` not `app`.

**Comment by pka420** [comment]
Check the PR #35

**Comment by South-Paw** [comment]
Ah right, Netlify used to redirect their .com to .app but must have ceased doing that at some point

**Comment by pka420** [comment]
Yeah they do be like that.
