### ISSUE TITLE
Storybook: not found

### ISSUE THREAD

**Issue by talentlessguy** [South-Paw/react-vector-maps#5]
I can't use the components because Storybook is unavailable. Pls help!

**Comment by South-Paw** [comment]
Hi there, thanks for raising an issue.

Could you please provide a little more detail so I can help you;

* are you unable to reach the demo storybook (https://react-vector-maps.netlify.com)?
* or is there an issue with the library after you've installed it to your project?

**Comment by talentlessguy** [comment]
@South-Paw there is a problem with demo storybook. When I open it writes "Not found" but in some seconds it shows the demo. Is it a Storybook problem? or with this repository?

**Comment by South-Paw** [comment]
That is a storybook thing and has nothing to do with the repository...
