### ISSUE TITLE
Russian map is outdated

### ISSUE THREAD

**Issue by talentlessguy** [South-Paw/react-vector-maps#6]
Russian map doesn't have Crimea which was added in 2014 to the territory of Russia. Please update the map.

[Wikipedia map SVG](https://ru.wikipedia.org/wiki/%D0%A4%D0%B0%D0%B9%D0%BB:Blank_map_of_Russia-gray.svg)

**Comment by South-Paw** [comment]
I don't make or manage the maps, I just used them with attribution to [MapSVG](http://mapsvg.com/maps/) who created them - this is stated clearly in the readme as well.

You could possibly follow up with them and ask them to do and update or whatever or you [can create your own SVG map and load it yourself](https://react-vector-maps.netlify.com/?path=/story/%F0%9F%93%96-documentation--using-your-own-svg-for-a-map).

Closing as not an issue with the repo.
