### ISSUE TITLE
Map Zoom

### ISSUE THREAD

**Issue by MatheusRV** [South-Paw/react-vector-maps#7]
Is possible to implement Zoom?

**Comment by South-Paw** [comment]
Hey, thanks for this suggestion. Zoom isn't a feature that I think is within this components responsibilities.

If you are looking for zoom, you could probably wrap the vector map component in another component which has event listeners for mouse scroll and a +/- button. The events could change a CSS transform property on the vector map or its container which may give you a zoom like effect on the map.
